modLoader="javafml" #mandatory
loaderVersion="[37,)"
license="MIT Licence"
[[mods]]
modId="detailab"
version="${file.jarVersion}"
displayName="Detail Armor Bar"
logoFile="icon.png"
authors="RedLime"
credits="snessim, Heamaci"
description='''Show more details of armors in Armor bar!'''
displayURL="https://github.com/RedLime/DetailArmorBar/tree/1.18-forge"
[[dependencies.detailab]]
    modId="forge"
    mandatory=true
    versionRange="[37,)"
    ordering="NONE"
    side="CLIENT"
[[dependencies.detailab]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="CLIENT"